name: Quran App CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flet-cli
          flet --version
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Accept licenses
        run: |
          yes | sdkmanager --licenses || true
          flutter doctor --android-licenses
      
      - name: Build APK
        run: |
          # Standard Flet build command for Android
          flet build android

      - uses: actions/upload-artifact@v4
        with:
          name: quran-app-apk
          path: dist/*.apk
          retention-days: 7

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flet-cli
          flet --version
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      
      - name: Build Windows
        run: |
          # Standard Flet build command for Windows
          flet build windows
      
      - uses: actions/upload-artifact@v4
        with:
          name: quran-app-windows
          path: dist/*.exe
          retention-days: 7

  build-release:
    needs: [build-android, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Quran App v${{ env.BUILD_VERSION }}
          body: |
            تطبيق القرآن الكريم متعدد المنصات
            
            يشمل:
            - إصدار Android (APK)
            - إصدار Windows (EXE)
          draft: false
          prerelease: false
          files: |
            artifacts/quran-app-apk/*.apk
            artifacts/quran-app-windows/*.exe
