name: Quran App Builds (Linux, macOS, Windows, Android, iOS)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2
  APP_NAME: "القرآن الكريم"
  APP_ID: "com.quran.app"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate cache key
        id: cache-key
        run: echo "key=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

  build-linux:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/build
          key: ${{ runner.os }}-linux-${{ needs.setup.outputs.cache-key }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          
      - run: |
          flutter config --no-analytics
          flet build linux \
            --verbose \
            --build-number=$BUILD_NUMBER \
            --build-version=$BUILD_VERSION \
            --app-name="$APP_NAME" \
            --bundle-id="$APP_ID"
            
      - uses: actions/upload-artifact@v4
        with:
          name: quran-linux-build
          path: build/linux
          retention-days: 7

  build-windows:
    needs: setup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/build
          key: ${{ runner.os }}-windows-${{ needs.setup.outputs.cache-key }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - run: |
          flutter config --no-analytics
          flet build windows \
            --verbose \
            --no-rich-output \
            --build-number=$env:BUILD_NUMBER \
            --build-version=$env:BUILD_VERSION \
            --app-name="$env:APP_NAME" \
            --bundle-id="$env:APP_ID"
            
      - uses: actions/upload-artifact@v4
        with:
          name: quran-windows-build
          path: build/windows
          retention-days: 7

  build-macos:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/build
          key: ${{ runner.os }}-macos-${{ needs.setup.outputs.cache-key }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - run: |
          flutter config --no-analytics
          flet build macos \
            --verbose \
            --build-number=$BUILD_NUMBER \
            --build-version=$BUILD_VERSION \
            --app-name="$APP_NAME" \
            --bundle-id="$APP_ID.macos"
            
      - uses: actions/upload-artifact@v4
        with:
          name: quran-macos-build
          path: build/macos
          retention-days: 7

  build-android:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/build
          key: ${{ runner.os }}-android-${{ needs.setup.outputs.cache-key }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - run: |
          flutter config --no-analytics
          flet build apk \
            --verbose \
            --build-number=$BUILD_NUMBER \
            --build-version=$BUILD_VERSION \
            --app-name="$APP_NAME" \
            --bundle-id="$APP_ID.android"
            
      - run: |
          flet build aab \
            --verbose \
            --build-number=$BUILD_NUMBER \
            --build-version=$BUILD_VERSION \
            --app-name="$APP_NAME" \
            --bundle-id="$APP_ID.android"
            
      - uses: actions/upload-artifact@v4
        with:
          name: quran-android-apk
          path: build/apk
          retention-days: 7
          
      - uses: actions/upload-artifact@v4
        with:
          name: quran-android-aab
          path: build/aab
          retention-days: 7

  build-ios:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/build
          key: ${{ runner.os }}-ios-${{ needs.setup.outputs.cache-key }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - run: |
          flutter config --no-analytics
          flet build ipa \
            --verbose \
            --build-number=$BUILD_NUMBER \
            --build-version=$BUILD_VERSION \
            --app-name="$APP_NAME" \
            --bundle-id="$APP_ID.ios"
            
      - uses: actions/upload-artifact@v4
        with:
          name: quran-ios-ipa
          path: build/ipa
          retention-days: 7

  deploy:
    needs: [build-linux, build-windows, build-macos, build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Quran App v${{ env.BUILD_VERSION }} (${{ env.BUILD_NUMBER }})
          body: |
            Quran App builds for all platforms:
            - Linux
            - Windows
            - macOS
            - Android (APK & AAB)
            - iOS (IPA)
          draft: false
          prerelease: false
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Upload artifacts to release
        run: |
          gh release upload $GITHUB_REF_NAME ./artifacts/**/*
