name: Build APK and IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy
        pip install buildozer

    - name: Build APK
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-8-jdk unzip
        pip install Cython==0.29.21
        buildozer -v android debug

    - name: Build IPA
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install python3
        pip3 install --upgrade pip
        pip3 install kivy
        pip3 install briefcase
        briefcase create iOS
        briefcase build iOS
        briefcase package iOS
